#!/bin/bash

clear

BIG=$PWD
LM=$(echo '\033[95m')
GREENG='\033[1m\033[92m'
RESTORE=$(echo '\033[0m')
CYAN=$(echo '\033[36m')

clear

trash="ls ~/.Trash | wc -l | tr -d ' '"
trashf=$(eval $trash)
trashDS="ls ~/.Trash/.DS_Store | wc -l | tr -d ' '"
trashDSE=$(eval $trashDS)
trash1=$(($trashf + $trashDSE))
trashls="ls -la ~/.Trash"
trashlse=$(eval $trashls)
trashpath="ls -la -d -1 ~/.Trash"
trashpathe=$(eval $trashpath)
trashsize="du -sh ~/.Trash | cut -f1 | tr -d ' '"
trashsizee=$(eval $trashsize)

clear

downl="ls ~/Downloads | wc -l | tr -d ' '"
downlf=$(eval $downl)
downDS="ls ~/Download/.DS_Store | wc -l | tr -d ' '"
downDSE=$(eval $downDS)
down1=$(($downlf + $downDSE))
downls="ls -la ~/Downloads"
downlse=$(eval $downls)
downpath="ls -la -d -1 ~/Downloads"
downpathe=$(eval $downpath)
downlsize="du -sh ~/Downloads | cut -f1 | tr -d ' '"
downlsizee=$(eval $downlsize)

clear

cache="ls ~/Library/Caches/ | wc -l | tr -d ' '"
cachef=$(eval $cache)
cacheDS="ls ~/Library/Caches/*.DS_Store | wc -l | tr -d ' '"
cacheDSE=$(eval $cacheDS)
cache1=$(($cachef + $cacheDSE))
cachels="ls -la ~/Library/Caches/"
cachelse=$(eval $cachels)
cachepath="ls -l -d -1 ~/Library/Caches"
cachepathe=$(eval $cachepath)
cachesize="du -sh ~/Library/Caches/ | cut -f1 | tr -d ' '"
cachesizee=$(eval $cachesize)

clear

yes='[y]'
no='[n]'
Exit='[q]'
skip='[a]'

echo "$CYAN"
clear
echo "What do you want to delete?$RESTORE"
echo "\033[95mTo delete your...$RESTORE"
echo "Cache: 1 ($cache1 files) ($cachesizee)"
echo "Trash: 2 ($trash1 files) ($trashsizee)"
echo "Downloads: 3 ($down1 files) ($downlsizee)"
echo "Quit: q"
printf "\n"
read -p $'\e[7mDelete\e[0m: ' ans
param_1=0

ft_load() {
echo "\033[93mSuppression en cours...\n$RESTORE"
duration=100
elapsed=$param_1
barsize=$((`tput cols` - 60))
unity=$(($barsize / $duration))
increment=$(($barsize%$duration))
skip=$(($duration/($duration-$increment)))
curr_bar=0
prev_bar=
if (( $elapsed <= 100 )) ; then

	color=$((($elapsed*100)/$duration))
	if (($color <= 25)) ; then
		colorvar='\033[93m'
	elif (($color > 25 && $color <=50)) ; then
		colorvar='\033[33m'
	elif (($color > 50 && $color <=75)) ; then
		colorvar='\033[96m'
	else
		colorvar='\033[92m'
		fi
  # Elapsed
prev_bar=$curr_bar
  let curr_bar+=$elapsed
  [[ $increment -eq 0 ]] || {  
    [[ $skip -eq 1 ]] &&
      { [[ $(($elapsed%($duration/$increment))) -eq 0 ]] && let curr_bar++; } ||
    { [[ $(($elapsed%$skip)) -ne 0 ]] && let curr_bar++; }
  }
  [[ $elapsed -eq 1 && $increment -eq 1 && $skip -ne 1 ]] && let curr_bar++
  [[ $(($barsize-$curr_bar)) -eq 1 ]] && let curr_bar++
  [[ $curr_bar -lt $barsize ]] || curr_bar=$barsize
  printf "	"
  for (( filled=0; filled<=$curr_bar; filled++ )); do
    printf "${colorvar}▇$RESTORE"
  done

  # Remaining
  for (( remain=$curr_bar; remain<$barsize; remain++ )); do
    printf " "
  done

  # Percentage
  printf "| %s%%" $(( ($elapsed*100)/$duration))

  # Return
  sleep 1
  printf "\r"
fi
printf "\n"
}

fonct_1()
{
	if (($cache1 == 0)) ; then
		clear
		echo "\033[1m\033[91mIl n'y a rien a supprimer !$RESTORE"
		sleep 1.5
		sh $0
	else
		clear
		echo "\033[95mYour are about to delete :$RESTORE"
		sleep 0.3
		printf "\n"
		echo "$cachepathe"
		echo "----------------------------"
		echo "$cachelse"
		sleep 0.2
		printf "\n"
		echo "${GREENG}Are you sure to Delete all files ?$RESTORE"
		read -p $' \033[93mEnter y or n or press "q" to back to the menu\033[0m :' nom
		if [[ "$nom" == $yes ]] ; then
			clear
			echo "\033[1m\033[91mSuppression des fichiers$RESTORE"
			printf "."
			sleep 1
			printf "."
			sleep 1
			printf ".\n"
			rm -rf ~/Library/*cache*
			rm -rf ~/Library/Caches/*
			rm -rf ~/Library/Caches/*.DS_Store
			echo "\033[4mSuppression cache complete..."
			sleep 0.4
			echo "${GREENG}Success!$RESTORE"
			sleep 1.5
			sh $0
		elif [[ "$nom" == $no ]] ; then
			clear
			echo "$cachepathe"
			echo "--------------------------"
			echo "$cachelse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ? :$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				sh $0
			else
				cd ~
				mkdir tempcash
				cd ~/Library/Caches
				mv $delete ~/tempcash
				rm -rf *
				rm -rf *.DS_Store
				cd ~
				cd ~/tempcash
				mv $delete ../Library/Caches
				rm -rf ~/tempcash
				cd $BIG
				sh $0
			fi
		else
			clear
			sh $0
		fi
	fi	
}

fonct_21()
{
	clear
	trash2="ls ~/.Trash | wc -l | tr -d ' '"
	trashf2=$(eval $trash2)
	trashDS2="ls ~/.Trash/.DS_Store | wc -l | tr -d ' '"
	trashDSE2=$(eval $trashDS2)
	trash2=$(($trashf2 + $trashDSE2))
	clear
}

fonct_2()
{
	if (($trash1 == 0)) ; then
		clear
		echo "\033[1m\033[91mIl n'y a rien a supprimer !$RESTORE"
		sleep 1.5
		sh $0
	else
		clear
		echo "\033[95mYou are about to delete :$RESTORE"
		sleep 0.3
		printf "\n"
		echo "$trashpathe"
		echo "----------------------------"
		echo "$trashlse"
		sleep 0.2
		printf "\n"
		echo "${GREENG}Are you sure to Delete all files ?$RESTORE"
		read -p $'	\033[93mEnter y or n or "q" to back to the menu :\033[0m' nom
		if [[ "$nom" == $yes ]] ; then
			fonct_21
			while (($trash2 != 0)) ; do
				rmf="ls -a ~/.Trash | head -3 | tail -1"
				rmfe=$(eval $rmf)
				rm -rf ~/.Trash/"$rmfe" 
				fonct_21
				if ((trash2 != 0)) ; then
					param_1=$(((($trash1 / $trash2) * 100) / $trash1))
					ft_load
				fi
			done
			echo "\033[4mSuppression trash complete...$RESTORE"
			sleep 1
			echo "${GREENG}Success!$RESTORE"
			sleep 1.5
			sh $0
		elif [[ "$nom" == $no ]] ; then
			clear
			echo "$trashpathe"
			echo "-------------------------"
			echo "$trashlse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ?$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				sh $0
			else
				cd
				mkdir Trash
				cd ~/.Trash
				echo $delete
				sleep 5
				mv $delete ../Trash/
				echo $(ls -la ~/.Trash)
				sleep 5
				fonct_21
				while (($trash2 != 0)) ; do
					rmf="ls -a ~/.Trash | head -3 | tail -1"
					rmfe=$(eval $rmf)
					rm -rf ~/.Trash/"$rmfe" 
					fonct_21
					if ((trash2 != 0)) ; then
						param_1=$(((($trash1 / $trash2) * 100) / $trash1))
						ft_load
					fi
				done
				cd
				cd Trash
				mv $delete ../.Trash/
				cd
				rm -rf Trash
				cd $BIG
				sh $0
			fi 
		else
			clear
			sh $0
		fi
	fi	
}

fonct_3()
{
	if (($down1 == 0)) ;  then
		clear
		echo "\033[1m\033[91mIl n'y a rien a supprimer !$RESTORE"
		sleep 1.5
		sh $0
	else
		echo "\033[95mYou are about to delete :$RESTORE"
		sleep 0.3
		printf "\n"
		echo "$downpathe"
		echo "----------------------------"
		echo "$downlse"
		sleep 0.2
		printf "\n"
		echo "${GREENG}Are you sur to Delete all files ?$RESTORE"
		read -p "\033[93mEnter y or n or "q" to back to the menu :$RESTORE" nom
		if [[ "$nom" == $yes ]] ; then
			clear
			echo "\033[1m\033[91mSuppression des fichiers$RESTORE"
			printf "."
			sleep 1
			printf "."
			sleep 1
			printf ".\n"
			rm -rf ~/Downloads/*
			rm -rf ~/Downloads/.DS_Store
			echo "\033[4mSuppression downloads complete...$RESTORE"
			sleep 0.4
			echo "${GREENG}Success!$RESTORE"
			sleep 1.5
			sh $0
		elif [[ "$nom" == $no ]] ; then
			clear
			echo "$downpathe"
			echo "-----------------------"
			echo "$downlse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ? :$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				sh $0
			else
				cd
				mkdir Download_
				cd ~/Downloads
				mv $delete ../Download_
				rm -rf *
				rm -rf *.DS_Store
				cd ../Download_
				mv $delete ../Downloads
				cd
				rm -rf Download_
				cd $BIG
				sh $0
			fi
		else
			clear
			sh $0
		fi
	fi	
}

if (($ans == 1)) ; then
	fonct_1
elif (($ans == 2)) ; then
	fonct_2
elif (($ans == 3)) ; then
	fonct_3
elif (($ans == 12 || $ans == 21)) ; then
	if (($cache1 == 0 && $trash1 == 0)) ; then
		clear
		echo "\033[1m\033[91mIl n'y a rien a supprimer !$RESTORE"
		sleep 1.5
		sh $0
	elif (($cache1 == 0)) ; then
		clear
		echo "\033[91mLes caches sont vides$RESTORE"
		sleep 0.2
		printf "."
		sleep 0.3
		printf "."
		sleep 0.2
		printf "."
	elif (($trash1 == 0)) ; then
		clear
		echo "\033[91mIl n'y a rien a supprimer dans les Trash$RESTORE"
		sleep 0.2
		printf "."
		sleep 0.3
		printf "."
		sleep 0.2
		printf "."
	fi
	clear
	if (($cache1 != 0 && $trash1 != 0)) ; then
		clear
		echo "\033[95mYour are about to delete :$RESTORE"
		sleep 0.3
		printf "\n"
		echo "$cachepathe"
		echo "----------------------------"
		echo "$cachelse"
		printf "\n"
		echo "$trashpathe"
		echo "----------------------------"
		echo "$trashlse"
		sleep 0.2
		printf "\n"
		echo "\033[1m\033[91mAre you sure to Delete all files ?$RESTORE"
		read -p $'	\033[93mEnter y or n or press "q" to back to the menu\033[0m :' nom
		if [[ "$nom" == $yes ]] ; then
			clear
			echo "\033[1m\033[91mSuppression des fichiers$RESTORE"
			printf "."
			sleep 1
			printf "."
			sleep 1
			printf ".\n"
			rm -rf ~/Library/*cache*
			rm -rf ~/Library/Caches/*
			rm -rf ~/Library/Caches/*.DS_Store
			rm -rf ~/.Trash/*
			rm -rf ~/.Trash/.DS_Store
			echo "\033[4mSuppression cache complete...$RESTORE"
			sleep 0.4
			printf "\n"
			echo "\033[4mSuppresion trash complete...$RESTORE"
			printf "\n"
			echo "${GREENG}Success!$RESTORE"
			sleep 1.5
			sh $0
		elif [[ "$nom" == $no ]] ; then
			clear
			echo "$trashpathe"
			echo "-------------------------"
			echo "$trashlse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[91mPress "a" to skip$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ? :$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				sh $0
			elif [[ "$delete" == $skip ]] ; then
				clear
			else
				echo "$delete"
				cd
				mkdir Trash
				cd ~/.Trash
				mv $delete ../Trash
				rm -rf *
				rm -rf .DS_Store
				cd ../Trash
				mv $delete ../.Trash
				cd $BIG
			fi
			clear
			echo "$cachepathe"
			echo "--------------------------"
			echo "$cachelse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[91mPress "a" to skip$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ? :$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				cd
				cd $BIG
				sh $0
			elif [[ "$delete" == $skip ]] ; then
				clear
			else
				cd ~
				mkdir tempcash
				cd ~/Library/Caches
				mv $delete ~/tempcash
				rm -rf *
				rm -rf *.DS_Store
				cd ~
				cd ~/tempcash
				mv $delete ../Library/Caches
				rm -rf ~/tempcash
				cd $BIG
				sh $0
			fi
		fi
	elif (("$cache1 != 0  && $trash1 == 0")) ; then
		fonct_1
	elif (("$cache1 == 0  && $trash1 != 0")) ; then
		fonct_2
	fi
elif (($ans == 13 || $ans == 31)) ; then
	if (($cache1 == 0 && $down1 == 0)) ; then
		clear
		echo "\033[1m\033[91mIl n'y a rien a supprimer !$RESTORE"
		sleep 1.5
		sh $0
	elif (($cache1 == 0)) ; then
		clear
		echo "\033[91mLes caches sont vides$RESTORE"
		sleep 0.5
		printf "."
		sleep 0.5
		printf "."
		sleep 0.5
		printf "."
	elif (($down1 == 0)) ; then
		clear
		echo "\033[91mIl n'y a rien a supprimer dans les Download$RESTORE"
		sleep 0.5
		printf "."
		sleep 0.5
		printf "."
		sleep 0.5
		printf "."
	fi
	clear
	if (($cache1 != 0 && $down1 != 0)) ; then
		clear
		echo "\033[95mYour are about to delete :$RESTORE"
		sleep 0.3
		printf "\n"
		echo "$cachepathe"
		echo "----------------------------"
		echo "$cachelse"
		printf "\n"
		echo "$downpathe"
		echo "----------------------------"
		echo "$downlse"
		sleep 0.2
		printf "\n"
		echo "\033[1m\033[91mAre you sure to Delete all files ?$RESTORE"
		read -p $'	\033[93mEnter y or n or press "q" to back to the menu\033[0m :' nom
		if [[ "$nom" == $yes ]] ; then
			clear
			echo "\033[1m\033[91mSuppression des fichiers$RESTORE"
			printf "."
			sleep 1
			printf "."
			sleep 1
			printf ".\n"
			rm -rf ~/Library/*cache*
			rm -rf ~/Library/Caches/*
			rm -rf ~/Library/Caches/*.DS_Store
			rm -rf ~/Downloads/*
			rm -rf ~/Downloads/*.DS_Store
			echo "\033[4mSuppression cache complete...$RESTORE"
			sleep 0.5
			printf "\n"
			echo "\033[4mSuppresion downloads complete...$RESTORE"
			printf "\n"
			echo "${GREENG}Success!$RESTORE"
			sleep 1.5
			sh $0
		elif [[ "$nom" == $no ]] ; then
			clear
			echo "$downpathe"
			echo "-------------------------"
			echo "$downlse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[91mPress "a" to skip$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ? :$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				sh $0
			elif [[ "$delete" == $skip ]] ; then
				clear
			else
				cd
				mkdir Downloads_
				cd ~/Downloads
				mv $delete ../Downloads_
				rm -rf *
				rm -rf *.DS_Store
				cd ../Downloads_
				mv $delete ../Downloads
				rm -rf ~/Downloads_
				cd $BIG
			fi
			clear
			echo "$cachepathe"
			echo "--------------------------"
			echo "$cachelse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[91mPress "a" to skip$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ? :$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				cd
				cd $BIG
				sh $0
			elif [[ "$delete" == $skip ]] ; then
				clear
			else
				cd ~
				mkdir tempcash
				cd ~/Library/Caches
				mv $delete ~/tempcash
				rm -rf *
				rm -rf *.DS_Store
				cd ~
				cd ~/tempcash
				mv $delete ../Library/Caches
				rm -rf ~/tempcash
				cd $BIG
				sh $0
			fi
		fi
	elif (("$cache1 != 0  && $down1 == 0")) ; then
		fonct_1
	elif (("$cache1 == 0  && $down1 != 0")) ; then
		fonct_3		
	fi
elif (($ans == 23 || $ans == 32)) ; then
	if (($trash1 == 0 && $down1 == 0)) ; then
		clear
		echo "\033[1m\033[91mIl n'y a rien a supprimer !$RESTORE"
		sleep 1.5
		sh $0
	elif (($trash1 == 0)) ; then
		clear
		echo "\033[91mLes trash sont vides$RESTORE"
		sleep 0.5
		printf "."
		sleep 0.5
		printf "."
		sleep 0.5
		printf "."
	elif (($down1 == 0)) ; then
		clear
		echo "\033[91mIl n'y a rien a supprimer dans les Download$RESTORE"
		sleep 0.5
		printf "."
		sleep 0.5
		printf "."
		sleep 0.5
		printf "."
	fi
	clear
	if (($trash1 != 0 && $down1 != 0)) ; then
		clear
		echo "\033[95mYour are about to delete :$RESTORE"
		sleep 0.3
		printf "\n"
		echo "$trashpathe"
		echo "----------------------------"
		echo "$trashlse"
		printf "\n"
		echo "$downpathe"
		echo "----------------------------"
		echo "$downlse"
		sleep 0.2
		printf "\n"
		echo "\033[1m\033[91mAre you sure to Delete all files ?$RESTORE"
		read -p $'	\033[93mEnter y or n or press "q" to back to the menu\033[0m :' nom
		if [[ "$nom" == $yes ]] ; then
			clear
			echo "\033[1m\033[91mSuppression des fichiers$RESTORE"
			printf "."
			sleep 1
			printf "."
			sleep 1
			printf ".\n"
			rm -rf ~/.Trash/*.DS_Store
			rm -rf ~/.Trash/*
			rm -rf ~/Downloads/*
			rm -rf ~/Downloads/*.DS_Store
			echo "\033[4mSuppression Trash complete...$RESTORE"
			sleep 0.5
			printf "\n"
			echo "\033[4mSuppresion downloads complete...$RESTORE"
			printf "\n"
			echo "${GREENG}Success!$RESTORE"
			sleep 1.5
			sh $0
		elif [[ "$nom" == $no ]] ; then
			clear
			echo "$downpathe"
			echo "-------------------------"
			echo "$downlse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[91mPress "a" to skip$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ? :$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				sh $0
			elif [[ "$delete" == $skip ]] ; then
				clear
			else
				cd
				mkdir Downloads_
				cd ~/Downloads
				mv $delete ../Downloads_
				rm -rf *
				rm -rf *.DS_Store
				cd ../Downloads_
				mv $delete ../Downloads
				rm -rf ~/Downloads_
				cd $BIG
			fi
			clear
			echo "$trashpathe"
			echo "--------------------------"
			echo "$trashlse"
			printf "\n"
			echo "\033[91mPress "q" to go back to the menu$RESTORE"
			printf "\n"
			echo "\033[91mPress "a" to skip$RESTORE"
			printf "\n"
			echo "\033[93mWhat file(s) do you want to no delete ? :$RESTORE"
			read delete
			if [[ "$delete" == $Exit ]] ; then
				clear
				cd
				cd $BIG
				sh $0
			elif [[ "$delete" == $skip ]] ; then
				clear
				sh $0
			else
				cd
				mkdir Trash
				cd ~/.Trash
				mv $delete ../Trash
				rm -rf *
				rm -rf *.DS_Store
				cd ../Trash
				mv $delete ../.Trash
				cd
				rm -rf ~/Trash
				cd $BIG
				sh $0
			fi
		fi
	elif (("$trash1 != 0  && $down1 == 0")) ; then
		fonct_2
	elif (("$trash1 == 0  && $down1 != 0")) ; then
		fonct_3		
	fi
elif (($ans == 123 || $ans == 321 || $ans == 213 || $ans == 231)) ; then
	clear
	echo "\033[1m\033[91mSuppression des fichiers$RESTORE"
	printf "."
	sleep 1
	printf "."
	sleep 1
	printf ".\n"
	rm -rf ~/Library/*cache*
	echo "\033[4mSuppression cache complete..."
	sleep 0.8
	rm -rf ~/.Trash/*
	echo "Suppression trash complete..."
	sleep 0.8
	rm -rf ~/Downloads/*
	echo "Suppression Downloads complete...$RESTORE"
	sleep 1
	echo "${GREENG}Success!$RESTORE"
	sleep 1.5
	sh $0
elif (($ans == q)) ; then
	exit ;
else 
	echo "\033[91mNo File ...$RESTORE"
	sleep 1
	sh $0
fi
